---

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Upgrade all apt packages
  become: true
  apt:
    upgrade: dist

- name: Remove unnecessary apt packages
  become: true
  apt:
    autoremove: yes
