---

- name: Check if 00-keyboard.conf exists
  stat:
    path: /etc/X11/xorg.conf.d/00-keyboard.conf
  register: keyboard_conf_stat

- name: Create 00-keyboard.conf if it doesn't exist
  copy:
    content: ""
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf
    mode: 0644
  when: not keyboard_conf_stat.stat.exists

- name: Switch CapsLock to Esc
  become: yes
  replace:
    path: /etc/X11/xorg.conf.d/00-keyboard.conf
    regexp: '"terminate:ctrl_alt_bksp"$'
    replace: '"terminate:ctrl_alt_bksp,caps:escape_shifted_capslock"'
  when: keyboard_conf_stat.stat.exists or not keyboard_conf_stat.stat.exists # Always run, since we create it if it doesn't exist

- name: Ensure CapsLock is mapped to Esc (using blockinfile)
  become: yes
  blockinfile:
    path: /etc/X11/xorg.conf.d/00-keyboard.conf
    create: yes
    block: |
      Section "InputClass"
          Identifier "system-keyboard"
          MatchIsKeyboard "on"
          Option "XkbLayout" "us" # Or your preferred layout
          Option "XkbOptions" "terminate:ctrl_alt_bksp,caps:escape_shifted_capslock"
      EndSection
