---

# Set up workspaces so they are similar to i3

- name: Set dynamic workspaces to false
  ansible.builtin.command: dconf write /org/gnome/mutter/dynamic-workspaces false

- name: Set number of workspaces
  ansible.builtin.command: dconf write /org/gnome/desktop/wm/preferences/num-workspaces 8

- name: Configure switch-to-workspace keybindings
  ansible.builtin.command:
    cmd: "dconf write {{ item.key }} '{{ item.value }}'"
  loop:
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1", value: "['<Super>1']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2", value: "['<Super>2']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3", value: "['<Super>3']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4", value: "['<Super>4']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-5", value: "['<Super>5']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-6", value: "['<Super>6']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-7", value: "['<Super>7']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-8", value: "['<Super>8']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-9", value: "['<Super>9']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-10", value: "['<Super>0']" }

- name: Configure move-to-workspace keybindings
  ansible.builtin.command:
    cmd: "dconf write {{ item.key }} '{{ item.value }}'"
  loop:
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-1", value: "['<Super><Shift>1']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-2", value: "['<Super><Shift>2']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-3", value: "['<Super><Shift>3']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-4", value: "['<Super><Shift>4']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-5", value: "['<Super><Shift>5']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-6", value: "['<Super><Shift>6']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-7", value: "['<Super><Shift>7']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-8", value: "['<Super><Shift>8']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-9", value: "['<Super><Shift>9']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-10", value: "['<Super><Shift>0']" }
