---

- name: Install z-shell package
  apt:
    name: 
      - zsh
    state: present

- name: Check if .zshrc exists
  stat:
    path: /home/{{ username }}/.zshrc
  register: zshrc_stat

- name: Remove .zshrc if it exists and is not a symlink
  file:
    path: /home/{{ username }}/.zshrc
    state: absent
  when: zshrc_stat.stat.exists and not zshrc_stat.stat.islnk

- name: Unlink .zshrc if it's a symlink
  file:
    path: /home/{{ username }}/.zshrc
    state: absent
  when: zshrc_stat.stat.exists and zshrc_stat.stat.islnk

- name: Create symlink for .zshrc
  file:
    src: /home/{{ username }}/Projects/dotfiles-popos/main/common/files/home/zsh/.zshrc
    dest: /home/{{ username }}/.zshrc
    state: link
