# sudo apt update
- name: Update apt cache
  apt:
    update_cache: yes

# sudo apt upgrade
- name: Upgrade all packages
  apt:
    upgrade: dist

# sudo apt autoremove
- name: Remove unnecessary packages
  apt:
    autoremove: yes

- include_tasks: kitty.yml

- include_tasks: zsh.yml

- include_tasks: i3.yml
